{
 "title": "Fraud System Overview",
 "tags": [
  "fraud",
  "week4",
  "observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"fraud-service\"}[1m]))",
     "legendFormat": "fraud-service rps"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"transaction-service\"}[1m]))",
     "legendFormat": "transaction-service rps"
    }
   ]
  },
  {
   "title": "ML Inference Avg (5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fraud_ml_inference_latency_seconds_sum[5m])) / sum(rate(fraud_ml_inference_latency_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Fraud Processing Avg (5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fraud_processing_latency_seconds_sum[5m])) / sum(rate(fraud_processing_latency_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Decisions in Last 5 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(fraud_decisions_total[5m])) by (decision)",
     "legendFormat": "{{decision}}"
    }
   ]
  }
 ]
}